const names = {
  1: "Jammu & Kashmir",
  2: "Himachal Pradesh",
  3: "Punjab",
  4: "Chandigarh",
  5: "Uttarakhand",
  6: "Haryana",
  7: "NCT of Delhi",
  8: "Rajasthan",
  9: "Uttar Pradesh",
  10: "Bihar",
  11: "Sikkim",
  12: "Arunachal Pradesh",
  13: "Nagaland",
  14: "Manipur",
  15: "Mizoram",
  16: "Tripura",
  17: "Meghalaya",
  18: "Assam",
  19: "West Bengal",
  20: "Jharkhand",
  21: "Odisha",
  22: "Chhattisgarh",
  23: "Madhya Pradesh",
  24: "Gujarat",
  26: "Dadra & Nagar Haveli and Daman & Diu",
  27: "Maharashtra",
  29: "Karnataka",
  30: "Goa",
  31: "Lakshadweep",
  32: "Kerala",
  33: "Tamil Nadu",
  34: "Puducherry",
  35: "Andaman And Nicobar islands",
  36: "Telangana",
  37: "Andhra Pradesh",
  38: "Ladakh",
  97: "Other Territory"
};

const codes = {
  "Bihar": 10,
  "Sikkim": 11,
  "Arunachal Pradesh": 12,
  "Nagaland": 13,
  "Manipur": 14,
  "Mizoram": 15,
  "Tripura": 16,
  "Meghalaya": 17,
  "Assam": 18,
  "West Bengal": 19,
  "Jharkhand": 20,
  "Odisha": 21,
  "Chhattisgarh": 22,
  "Madhya Pradesh": 23,
  "Gujarat": 24,
  "Dadra & Nagar Haveli and Daman & Diu": 26,
  "Maharashtra": 27,
  "Karnataka": 29,
  "Goa": 30,
  "Lakshadweep": 31,
  "Kerala": 32,
  "Tamil Nadu": 33,
  "Puducherry": 34,
  "Andaman And Nicobar islands": 35,
  "Telangana": 36,
  "Andhra Pradesh": 37,
  "Ladakh": 38,
  "Other Territory": 97,
  "Jammu & Kashmir": 1,
  "Himachal Pradesh": 2,
  "Punjab": 3,
  "Chandigarh": 4,
  "Uttarakhand": 5,
  "Haryana": 6,
  "NCT of Delhi": 7,
  "Rajasthan": 8,
  "Uttar Pradesh": 9
};

module.exports = {
  names,
  codes
}